# Generated by Django 5.0.4 on 2024-04-15 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=450)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.user')),
            ],
        ),
    ]
