# Generated by Django 5.0.4 on 2024-04-17 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_alter_message_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='group_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.group'),
        ),
    ]
